### ISSUE TITLE
[Proposal] Build CiiMS 3 (C3) with Yii 2

### ISSUE THREAD

**Issue by charlesportwoodii** [charlesportwoodii/CiiMS#146]
CiiMS3 would be a complete rewrite of CiiMS to take advantage of Yii 2. This thread should serve as a common source to collect the feature requirements, suggestions, and improvements for CiiMS3.

------

### Current Tasks

- [ ] Assemble core team
- [ ] Define features, structure, and guideines
- [ ] Define modules
 - [ ] Installer
 - [ ] Dashboard
 - [ ] API
 - [ ] Social (?) (Should social be a core integration or a modular one?)

**Comment by abhi1693** [comment]
Hey buddy, I would like to work on this project with you. I have also been working on somthing similar. You can check it out [here](https://github.com/abhi1693/yii2-app-advanced-startup-kit)

**Comment by charlesportwoodii** [comment]
@abhi1693,

Thanks for reaching out, I'd love to have another contributor for CiiMS. Right now the purpose of this issue is to collect idea for new features, additions that CiiMS 3 should have in it (in addition to everything CiiMS 2 currently have), and define what it will actually look like.

**Comment by abhi1693** [comment]
Regarding your `Social` module, I think it should be modular. It should depend on the user whether to keep it or remove it from the app.

**Comment by ErsanJSano** [comment]
Hey @charlesportwoodii,
sign me up when you get on with this. I am interested in, initially small, tasks...so when you flesh things out hit me up with something.

**Comment by charlesportwoodii** [comment]
Hi @ErsanJSano! I can do that!

**Comment by charlesportwoodii** [comment]
Closing until future notice when startup of CiiMS 3 begins
