### ISSUE TITLE
Unable to Install (rewrites?)

### ISSUE THREAD

**Issue by pnd178** [charlesportwoodii/CiiMS#148]
Hi there,

I am trying to install ciims but I have be unable to pass the CHECK MYSQL CONNECTION on the install.php. After I submit the form the ciims jumps to ciims/migrate and I get a Not found.

Can you please tell me what I am doing wrong?

Best regards,
PD

**Comment by charlesportwoodii** [comment]
@pnd178,

I'm not able to replicate this on my development environment using ```dev-master```, so I have a couple of questions for you:

1. Which version are you using? A tagged release or the master branch?
2. Are you running Apache? CiiMS doesn't come with a .htaccess file, you'll need to provide one - or configure your webserver with mod_rewrite. (See http://www.yiiframework.com/doc/guide/1.1/en/quickstart.apache-nginx-config).

My guess is that you don't have rewrites enabled on your web server, or the right apache configuration in place - but I'd need more information to confirm that.

**Comment by pnd178** [comment]
Hi there,

There is a .htaccess on the ciims root.
This is his content:
Options +FollowSymLinks
IndexIgnore */*
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

#otherwise forward it ti index.php
RewriteRule . index.php

**Comment by charlesportwoodii** [comment]
@pnd178,

I see that you closed the issue. Did you resolve your problem? If not - can you provide answers to the questions listed in my previous comment?

Thanks

**Comment by pnd178** [comment]
Hi Charles,

Sorry I closed.

I am using the dev-master, and I have the .htaccess in the root and inside the protected folder.

What am I forgting?

Best regards,

**Comment by charlesportwoodii** [comment]
@pnd178,

Are you using Apache? And are you on Linux or Windows? Is mod_rewrite enabled?

That sounds like rewrites aren't enabled on your web server.

**Comment by pnd178** [comment]
Hi charles,

I am using Kubuntu 64-bits with apache and de mod_rewrite is enable, but I don't find any mention of it in the apache logs.

Can be it?

Best regards,

**Comment by pnd178** [comment]
Hi Charles,

I found the problem. since I am using the apache 2.4 the .htaccess and the mod_rewrite is diferent.

**Comment by charlesportwoodii** [comment]
@pnd178,

Glad you resolved the issue with your web-server.
