### ISSUE TITLE
Notice: Use of undefined constant DS - assumed 'DS' in ...

### ISSUE THREAD

**Issue by almix** [charlesportwoodii/CiiMS#150]
I've got notices about constant DS:

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 15

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 15

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 15

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 15

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 15

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 16

Notice: Use of undefined constant DS - assumed 'DS' in /Users/alexanderisaev/Sites/CiiMS/install.php on line 16

Warning: require_once(/Users/alexanderisaev/Sites/CiiMSDSvendorDSautoload.php): failed to open stream: No such file or directory in /Users/alexanderisaev/Sites/CiiMS/install.php on line 16

Fatal error: require_once(): Failed opening required '/Users/alexanderisaev/Sites/CiiMSDSvendorDSautoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.4.30/lib/php') in /Users/alexanderisaev/Sites/CiiMS/install.php on line 16

**Comment by charlesportwoodii** [comment]
@almix.

```git pull``` the master branch and it should work
