### ISSUE TITLE
Can't install. vendor/autoload.php is absent

### ISSUE THREAD

**Issue by almix** [charlesportwoodii/CiiMS#151]
try to install:

Warning: require_once(/Users/alexanderisaev/Sites/CiiMS/vendor/autoload.php): failed to open stream: No such file or directory in /Users/alexanderisaev/Sites/CiiMS/install.php on line 17

Fatal error: require_once(): Failed opening required '/Users/alexanderisaev/Sites/CiiMS/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.4.30/lib/php') in /Users/alexanderisaev/Sites/CiiMS/install.php on line 17

when try 'composer install', look in Terminal:

AlexandsaevsMBP:CiiMS alexanderisaev$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package php >=5.5.19 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by charlesportwoodii** [comment]
CiiMS 2 needs PHP 5.5 installed, specifically ```5.5.19```. Make sure you're using an upgraded version of PHP with whatever web server you are using.

```
- The requested package php >=5.5.19 could not be found.
```

**Comment by charlesportwoodii** [comment]
@almix,

Wanted to follow up with you regarding this. Can you post an update and let me know if you need further support? If not I'll go ahead and close this issue out.

Thanks
