### ISSUE TITLE
[RFF] [Open Question] Does CiiMS fulfill your needs?

### ISSUE THREAD

**Issue by charlesportwoodii** [charlesportwoodii/CiiMS#156]
Consider this an open request for feedback: Does CiiMS fulfill your needs? If so, are there are features you'd like to see? If it doesn't, could you elaborate why it doesn't fulfill your needs?

**Comment by Stiveknx** [comment]
Well, like another developers, I'm searching some alternative to WordPress ...

One thing, that makes wordpress a best option, is, his themes and plugins ..
Well, not sure if this is your idea for your CMS, but you think about getting a plugin or theme repository?

I've got a lot of Ideias to plugins that I'm missing, that also could be built-in with the system (to avoid the job to look for a plugin, I think they can be developed in a light way, so the system would be rich and fast)

Some ideia:
- Image resize (and something to "extend" the {image} tag, {image:300x250}

- Custom posts and Fields - yeah, like the wordpress ones. I would like to easily ccreate a "Projects" area, or an "Events" area, and keep it separate from another posts. I could create Custom Posts, and after it they came up in side Panel  so I can start easily start creating those posts, and in Main site, access the posts in URL like: "mysite.com/projects".
Also the custom fields, in events for example, I would need a "event date" field, or a "video field", for example, and, also with a custom tag in post to display it ...

- Users, and it's permissions. I would like to edit, what collaborators can do, and what editors can do, which areas they can access, and why not restrict posts or some specific posts to only registered users, or user group?

- Internal messaging system (to users communicate with each other)

- Add groups to Users ... I'm working on a system now, And I categorize then in a group, so I can easily list users by it's city (In my case, for example).

- Some Mail Subscribers system, like MailChimp (or think more about this ideia too).

- Advanced editor need more improvements. I could add / remove / move / disable for some users, some of the toolbar buttons (in the dashboard settings itself).

- Integrate Comments system - Option to choose: default,  disqus, facebook, Google +.

- Integrate with ad options - Like Adsense, and other programs. Google Adsense also have it's own API, not sure what It can do, but a "Earnings" graphic, would be a cool card.

Well, I've got millions of Ideias, I would like to contribute in a project like this one (with coding, and PR too, if developers Agree with it).

**Comment by charlesportwoodii** [comment]
@Stiveknx,

First off, thanks for the feedback. I can provide some insight into a few of those items - and as always would love to see a PR if you want to add in something to make CiiMS better. I see a lots of really good ideas and would be open to more discussion on most of them if there is a particular use case/desired implementation you'd like to see.

> Well, not sure if this is your idea for your CMS, but you think about getting a plugin or theme repository?

Themes are kind of a sore point right now, simply because there aren't a lot of them. That being said, CiiMS does have a [centralized themes repository](https://github.com/ciims/themes) (https://github.com/ciims/themes). All that data from this repo gets pulled into the themes section of the dashboard. From there you can browse all the available themes. The bigger issue is that there's only 2 public themes at the moment. Currently I'm working to add more themes to CiiMS, it just takes time. 

![capture](https://cloud.githubusercontent.com/assets/630969/6887666/2afb94ac-d62c-11e4-9dbb-af72fc06d8ee.PNG)

I'd _love_ to see more themes be built out and made public (most people don't want to make themes open source, which I understand).

> I've got a lot of Ideias to plugins that I'm missing, that also could be built-in with the system (to avoid the job to look for a plugin, I think they can be developed in a light way, so the system would be rich and fast)

There are also a few plugins - although they are mainly restricted to uploading https://github.com/charlesportwoodii/ciims-plugins-awsuploader, https://github.com/charlesportwoodii/ciims-plugins-rackspaceuploader.

I'm still working on a better delivery mechanism for them since they are used in PHP. I don't necessarily want to dump plugins to the ```vendor/``` folder, even though that's where they should go because it makes plugin management a big pain, especially when dealing with deployment tools.

One of the core ideas I'm working with is that plugins, should easily tie into CiiMS. The bigger issue I am facing is that most of those items would require custom hooks inside of CiiMS itself to offer it. At the moment I don't know what those hooks should be for plugins to work nicely with CiiMS/Yii, but would love to see something that improved upon what we have currently.

> Image resize (and something to "extend" the {image} tag, {image:300x250}

I love it. The controls for the ```{image}``` tag are all done in JavaScript, and the resizing can easily be done server side before the uploading component is triggered. I'd love to see a PR for this one, but can easily add it to the backlog.

> Custom posts and Fields - yeah, like the wordpress ones. I would like to easily ccreate a "Projects" area, or an "Events" area, and keep it separate from another posts. I could create Custom Posts, and after it they came up in side Panel so I can start easily start creating those posts, and in Main site, access the posts in URL like: "mysite.com/projects".
> Also the custom fields, in events for example, I would need a "event date" field, or a "video field", for example, and, also with a custom tag in post to display it ...

Currently this is _kinda_ doable via the content_type/view-layout selectors - there just isn't a way to enter custom content_types via the dashboard. Most of that is manual programmatic work, but it's designed in such a way internally that it could be automated as you suggested. I'd love to see some improvements to it.

> Users, and it's permissions. I would like to edit, what collaborators can do, and what editors can do, which areas they can access  and why not restrict posts or some specific posts to only registered users, or user group?

The RBAC for CiiMS is fairly straightforward. I'd love to see more granular improvements to it to allow for this kind of thing.

> Internal messaging system (to users communicate with each other)

What is the benefit of an internal messaging system for a blogging platform?

> Add groups to Users ... I'm working on a system now, And I categorize then in a group, so I can easily list users by it's city (In my case, for example).

CiiMS used to have groups, but it was removed to reduce complexity (the userbase at the time had no interest in it). If interest is shifting back towards that I'd be open to revisiting that discussion.

> Some Mail Subscribers system, like MailChimp (or think more about this ideia too).

This sounds more theme specific rather than something that CiiMS should provide IMO. For instance, the [promotional site](https://www.ciims.io) does this via a simple HTML form. What is the benefit of having CiiMS do this internally?

> Advanced editor need more improvements. I could add / remove / move / disable for some users, some of the toolbar buttons (in the dashboard settings itself).

The UI for the editor is simply push buttons to insert Markdown/HTML comments, all of which would be manually entered if the user so chose to do so. How exactly would removing an item from the toolbar be beneficial given that the underlying data is just Markdown?

> Integrate Comments system - Option to choose: default, disqus, facebook, Google +.

CiiMS has this. Currently you can switch between the built in commenting system or Disqus. The underlying system is setup though so that any JavaScript commenting platform can easily be integrated via the charlesportwoodiii/cii repo. Right now I'm working on a Discourse extension, facebook and Google+ would be good commenting systems to add in as well.

> Integrate with ad options - Like Adsense, and other programs. Google Adsense also have it's own API, not sure what It can do, but a "Earnings" graphic, would be a cool card.

Sounds like a good card to add. I'll have to look into the Adsense API to get a clearer picture of what that entails. So long as all of those options can be done in JavaScript I think this would be a great addition (cards are written entirely in JavaScript now).

**Comment by Stiveknx** [comment]
> Out of curiosity though, why not just upload a 300x250 image in the first place?

Let's say I can choose to display a 300x250 in blog home page / listing, and inside the post a 400x325, and also, show the fullscreen image using jQuery's fancybox (or related?)
I would need all of these sizes ...

> What is the benefit of an internal messaging system for a blogging platform?

Well, that depends if the project will be a *content management system* or just a blogging platform.
Wordpress, for example, is initially made to work as a blogging platform, but I can make it become a forum, a social network, or something else ... The last Project I've been working, Admin users can send messages to Editor users, sending tips, telling them what to write, and other stuff (It's a online newspaper). Maybe I doesn't need to be a built-in feature, but a plugin would be cool.

> This sounds more theme specific rather than something that CiiMS should provide IMO. For instance, the promotional site does this via a simple HTML form. What is the benefit of having CiiMS do this internally?

Can be worked on the theme, sure! But if I'm creating a theme, I don't wanna loose any time by configuring a newsletter, if the system already have its own. And I think is really used In a lot of blogs ...

>The UI for the editor is simply push buttons to insert Markdown/HTML comments, all of which would be manually entered if the user so chose to do so. How exactly would removing an item from the toolbar be beneficial given that the underlying data is just Markdown?

Maybe the removing option won't be that used, but add new items I think it would be very useful.

Sorry for bad English, Brazilian here ...

**Comment by charlesportwoodii** [comment]
> Sorry for bad English, Brazilian here ...

Your english is perfectly understandable. = )

> Let's say I can choose to display a 300x250 in blog home page / listing, and inside the post a 400x325, and also, show the fullscreen image using jQuery's fancybox (or related?) I would need all of these sizes...

I understand what you're saying now, the API could easily perform that task, however it would still be up to the theme to determine the presentation of that particular asset. I think the only problem with that is that the upload process will take longer, which can give the impression CiiMS is slow.

> Well, that depends if the project will be a content management system or just a blogging platform.
Wordpress, for example, is initially made to work as a blogging platform, but I can make it become a forum, a social network, or something else ... The last Project I've been working, Admin users can send messages to Editor users, sending tips, telling them what to write, and other stuff (It's a online newspaper). Maybe I doesn't need to be a built-in feature, but a plugin would be cool.

While CiiMS started out to be more of a CMS, the latest pivot is to be more of a blogging platform. Wordpress works as a CMS because it _can_ do everything - it has hooks for every possible action and re-action.

> Can be worked on the theme, sure! But if I'm creating a theme, I don't wanna loose any time by configuring a newsletter, if the system already have its own. And I think is really used In a lot of blogs ...

Follow up question: Ideally, CiiMS would send a single API request on publication to a service like MailChimp that would handle all the outgoing email transactions and so forth. Is that what you were thinking? I think so long as there is a process to offload the majority of the workload of sending emails, that would be a great addition to CiiMS.

The API doesn't support a lot of those things at the moment, so I'll need to work out how exactly a few of these items will work. Let me have a few days to figure out the best way to integrate some of these items, and I'll follow up here. In the meantime, if you have any other ideas, or any PR you'd like to see feel free to contribute.

Thanks = )

**Comment by Stiveknx** [comment]
>which can give the impression CiiMS is slow.

Yes, and it's going to give this impression, but there's alternatives...
Like: Show a Progress bar with description:
0% - Uploading image
33% - Creating "Thumbnail Name"
66% - Creating "Thumbnail Another Name"
100% - Image Uploaded successfully.

If there's any progress showing what the system is doing, there's never gonna be a impression that it's slow, it's just doing heavy, hard and slow operations, that the user need ..

I would like to contribute with PR, but, since I'm not good in organization, I'll wait for you check, what can be done, what should be done, what should be a plugin, what should be built in, etcs ...

**Comment by charlesportwoodii** [comment]
@Stiveknx,

I'm still trying to work out a few details for a few of these items as they are a lot more involved. In the meantime, here's what I think would be good starting points to get added if you want to tackle these items first:

> Integrate Comments system - Option to choose: default, disqus, facebook, Google +.

Adding in Facebook & Google+ comments should be relatively straight-forward, here's what that basically boils down to:
1. Updating the [GeneralSettings model](https://github.com/charlesportwoodii/CiiMS/blob/master/protected/models/settings/GeneralSettings.php) to support those enabling and storing those properties.
2. Creating a Facebook/GooglePlus comment widget (@see https://github.com/charlesportwoodii/cii/tree/master/widgets/comments)
3. Adding & compiling the necessary JavaScript following patterns defined in the cii/assets/js repo (@see https://github.com/charlesportwoodii/cii/tree/master/assets/js).
4. Updating translations
5. Testing
6. From a UX perspective, it may be worthwhile to explore how to display toggling of multiple commenting systems. Right now you can turn Disqus on or off, which toggles between default comments and Disqus comments. If we're supporting multiple third party comment systems there should be a way to toggle between all of those rather than dealing with a single checkbox which is used currently.

> Integrate with ad options - Like Adsense, and other programs. Google Adsense also have it's own API, not sure what It can do, but a "Earnings" graphic, would be a cool card.

This is a great idea for a dashboard card. Developing cards are fairly straightforward: you can checkout the documentation for them [here](https://docs.ciims.io/cards.html). There is also [several](https://github.com/charlesportwoodii/ciims-basic-card) [other](https://github.com/charlesportwoodii/ciims-newrelic-responsetime-card) [great](https://github.com/charlesportwoodii/ciims-analytics-card) [examples](https://github.com/charlesportwoodii/ciims-weather-card2) for you to reference

**Comment by charlesportwoodii** [comment]
This isn't gaining any traction. Closing this issue for now. Open to further discussion as needed/wanted.
