### ISSUE TITLE
Allow CiiRedisCache to Connect to a Redis Unix Socket

### ISSUE THREAD

**Issue by Mosely** [charlesportwoodii/CiiMS#159]
Hi again,

Could you modify CiiRedisCache to allow it to connect to Redis via a unix socket?  This could be useful for those of us who run Redis locally alongside the CiiMS web server and intend to use only unix socket connections.

**Comment by charlesportwoodii** [comment]
@Mosely,

Available in the latest ```master``` branch. Implements as follows:

```
'cache' => array(
	'class' => 'CiiRedisCache',
	'server' => array(
		'db' => 1,
		'socket' => '/tmp/redis.sock'
	),
)
```

Note that you'll need to reconfigure Redis to use unix sockets rather than TCP. I believe the configuration you need for ```/etc/redis/redis.conf``` is:

```
port 0
unixsocket /tmp/redis.sock
unixsocketperm 766
```

The socket will also need to be readable by your web server.
