### ISSUE TITLE
Not downnloading ciims-plugins/awsuploader

### ISSUE THREAD

**Issue by kavitama** [charlesportwoodii/CiiMS#163]
Hi Charles,

Started on a brand new Cetnos 7, php 5.6.10 web server.
Ran composer create-project --prefer-dist --stability=dev charlesportwoodii/ciims sitetest dev-master

Got the following error:
  - Installing ciims-plugins/awsuploader (1.0.3)
    Downloading: Connecting...    Failed to download ciims-plugins/awsuploader from dist: The "https://api.github.com/repos/charlesportwoodii/CiiAWSUploader/zipball/eec854a1ae1f419caaa7abbe241ffc6d29eb1694" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing ciims-plugins/awsuploader (1.0.3)
    Cloning eec854a1ae1f419caaa7abbe241ffc6d29eb1694
  [RuntimeException]
  Failed to clone https://02abb4ab20834d9c94efd2672214b49965382b8d:***@github
  .com/charlesportwoodii/CiiAWSUploader.git, git was not found, check that it
   is installed and in your PATH env.
  sh: git: command not found

Any idea what am I doing wrong?

**Comment by charlesportwoodii** [comment]
Hi Kavitama,

```
git, git was not found, check that it is installed and in your PATH env. sh: git: command not found
```

Composer is trying to fall back on ```git``` and it isn't installed. Install git then try re-running the ```create-project``` command.

Looks like you're on Windows (?) Git can be downloaded for Windows at: https://git-scm.com/download/win.

That being said, I'd highly recommend running CiiMS on a Linux machine or VM.

**Comment by kavitama** [comment]
Hi Charles,

I installed composer on a Linux Centos 7.1.1503 in the usual way 
(curl -sS https://getcomposer.org/installer | php) and then moved to global (mv composer.phar /usr/local/bin/composer)

I dont understand why is falling back on GIT

**Comment by charlesportwoodii** [comment]
@kavitama,

The git fallback is for when either there is an issue on Github or Packagist that prevent either of them from providing a zip package - I don't know those exact circumstances however. Pulling a tag from git and fetching a premade tarball is effectively the same action though.

On CentOS, you can install git with ```yum install git```.
