### ISSUE TITLE
Installtion Error "web/migrate" 404 ERROR not Found

### ISSUE THREAD

**Issue by GaneshKandu** [charlesportwoodii/CiiMS#168]
HI ,Getting ERROR during installation  
<h1>Not Found</h1>
<p>The requested URL /ciims/index.php was not found on this server.</p>
<hr>
<address>Apache/2.2.31 (Unix) Server at &lt;IP-address&gt; Port 80</address>

downloaded from https://github.com/charlesportwoodii/CiiMS/archive/2.0.0.zip
and successfully run composer with no error
getting error on "web/migrate" page not found after first step of Connect to MySQL Database

**Comment by charlesportwoodii** [comment]
@GaneshKandu,

Your Apache webroot should be pointed to ```/path/to/ciims/web``` rather than ```/path/to/ciims```. The ```web``` directory should be the only directory that is publicly accessible. If you're getting routes for ```web/<path>```, something is wrong with your Apache config.

```
# Set document root to be "basic/web"
DocumentRoot "/path/to/ciims/web"

<Directory "/path/to/ciims/web">
    # use mod_rewrite for pretty URL support
    RewriteEngine on
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php

    # ...other settings...
</Directory>
```

**Comment by GaneshKandu** [comment]
Hi, @charlesportwoodii 
I don't have authentication to edit httpd.conf
how i can try using .htaccess or other methods

**Comment by charlesportwoodii** [comment]
@GaneshKandu,

You can use the following .htaccess file in the ```web/``` directory to handle Yii's rewrites:

```
Options +FollowSymLinks
IndexIgnore */*
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

#otherwise forward it ti index.php
RewriteRule . index.php
```

However, you still need to map Apache to point to ```/path/to/ciims/web``` as your webroot/documentroot, as that is where the bootstrap file is. CiiMS won't be able to load unless that is where your docroot is pointed to.
