### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kalyan312** [charlesportwoodii/CiiMS#169]
This project is good. But follow all documentation of install. but fail. also i got error like `
Warning: require(C:\xampp\htdocs\cc\web/protected/modules/install/init.php): failed to open stream: No such file or directory in C:\xampp\htdocs\cc\web\install.php on line 29

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\cc\web/protected/modules/install/init.php' (include_path='C:\xampp\htdocs\cc\vendor/phpseclib/phpseclib/phpseclib;C:\xampp\php\PEAR') in C:\xampp\htdocs\cc\web\install.php on line 29`
i tried both local and remote. windows and linux system.

**Comment by charlesportwoodii** [comment]
@kalyan312,

You installed CiiiMS via composer, correct?

```
composer create-project --prefer-dist --stability=dev charlesportwoodii/ciims {path| 2.0.2
```

The error you indicated implies _either_ you don't have all the composer dependencies installed _or_ that you're webserver configuration is wrong. Your webserver should be mapped to the ```web``` directory *not* the root directory. What does your Apache/Nginx configuration look like? 

Do you get the _exact_ same error on both Windows and Linux? Using the above provided command I was able to install CiiMS onto a fresh Linux server without any issues.

**Comment by kalyan312** [comment]
WOW!! Its working. I did not install git command first time. when i installed it and try to download again, I get a full fresh project. Thanks.

**Comment by kalyan312** [comment]
I faced another Problem when the system trying to create admin
url is: http://news.bevysoft.com/web/createadmin
error is:
` Fatal error: Call to undefined function password_hash() in /home/bevysoft/public_html/news/protected/modules/install/models/UserForm.php on line 166`

**Comment by mjiong** [comment]
are you add the vendor folder into your project?

**Comment by charlesportwoodii** [comment]
@kalyan312,

A couple of items to answer your questions:

1. I remove the URL you posted in your previous comment for security concerns. I don't recommend posting URL's to un-configured services.
2. The ```vendor``` folder is not provided with on ```git clone``` for several reasons -- the security of _your_ application and being able to independently verify you have untampered packages and limitations on my upload speed being among them.
3. Your web server (DocumentRoot) needs to be configured to point to the ```web``` directory. If the ```web``` directory appears in URL of your application, your web server is incorrectly configured, and CiiMS will not install correctly (or possibly at all).
4. CiiMS has a minimum PHP dependency of ```5.5.0``` (defined in composer.json) which contains the ```password_hash``` functions. The error you listed:
```
Fatal error: Call to undefined function password_hash()
```
Means that your web host is running a PHP version _less_ than ```5.5.0```. Upgrade the PHP version on your web server. Your hosting provider can provide direction on this if you aren't certain how to go about this.

PHP ```5.4``` is no longer supported, and PHP ```5.5``` will only be receiving security fixes until _July_ of this year. I highly recommend you upgrade to _at least_ ```5.6```. See the following document on php.net for more information: https://secure.php.net/supported-versions.php

**Comment by charlesportwoodii** [comment]
@kalyan312,

Were you able to resolve your issue?

**Comment by charlesportwoodii** [comment]
Closing due to lack of response. If the issue persists feel free to re-open it and discuss.
