### ISSUE TITLE
Cannot install  CiiMS 

### ISSUE THREAD

**Issue by duongcuong96** [charlesportwoodii/CiiMS#171]
i follow this official gui :
```
composer create-project --prefer-dist --stability=dev charlesportwoodii/ciims {} 2.0.2
cd {path}
composer dump-autoload -o
```
After done that , everything ok , but i after i try to install CiiMS via http://localhost/ciims/web/index.php , enter user name , password and db name then i press submit button , after that :
```
The requested URL /ciims/index.php was not found on this server.
```
Now i still cannot install CiiMS , please help me , thanks !

**Comment by charlesportwoodii** [comment]
The installation guide outlines everything you need to do to install CiiMS. Please read the documentation at https://docs.ciims.io/installation.html _thoroughly_. The issues you have outlined are covered in the installation guide.

1. If you're experimenting with CiiMS on your local machine, I _highly_ recommend you use the provided Vagrant box, as I cannot support for irregularities with your localhost web server configuration. How do to this is outlined in the installation guide.

2. While it's possible to run CiiMS in a sub-folder configuration like you are doing, I _highly_ recommend against it. Again, this out outlined in the installation guide.

3. Looking at your error, your web server configuration is not pointed to `/ciims/web/index.php` as outlined in the installation guide. You _must_ point your web server to this bootstrap file. Additionally, you must ensure that your web server support URL rewriting (Apache this is `ModRewrite`).

All of these are clearly outlined in the aforementioned documentation. Additionally, if you're wanting to try CiiMS locally, please use the Vagrant configuration outlined in the guide, as it _greatly_ simplifies installation and resolves many of the issues developers and user face when testing CiiMS locally/on Windows.

**Comment by charlesportwoodii** [comment]
If you're using Apache on Windows (WAMP) stack, please see #168 for how to properly configure your web server

**Comment by duongcuong96** [comment]
Thanks you so much ! 
After add `.htaccess` to my `web` folder it worked ! 

`` 
.htaccess conttent : 

Options +FollowSymLinks
IndexIgnore */*
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

#otherwise forward it ti index.php
RewriteRule . index.php

```

**Comment by mjiong** [comment]
@charlesportwoodii  hei man.I saw that CiiMS to no longer offer public hosting services.Is that the CiiMs no longer open sources?I am sorry that I am poor in english.

**Comment by charlesportwoodii** [comment]
@mjiong,

CiiMS is still open source, and remains licensed under the [MIT License](https://github.com/charlesportwoodii/CiiMS/blob/master/LICENSE.md).

**Comment by mjiong** [comment]
@charlesportwoodii ok，I know.thanks.
