### ISSUE TITLE
Problem with user update

### ISSUE THREAD

**Issue by whsecurity** [charlesportwoodii/CiiMS#172]
Hello I installed ciims through vagrant. Everything seems ok but I have this strange problem. I created a new user and after that I tried to change his personal details from User to collaborator, author or everything else. After update user button the spinner does a short cyrcle and after that it stays like that. If I change to another user / tab and come back again everything are as initally (After the creation)

**Comment by charlesportwoodii** [comment]
Hi @whsecurity,

Sorry for the trouble. It looks like some debug code got pulled in whenever the last merge occurred. It should be patched now. You can correct it inside the Vagrant box either by:

1. SSH-ing into the box and updating the source code
```
vagrant ssh
cd /var/www
git pull
```

2. Or by destroying and re-provisioning the box
```
vagrant destroy
vagrant up --provision
```

That should resolve the issue for you.

**Comment by whsecurity** [comment]
After the 
`vagrant destroy
vagrant up --provision`

I encounter this error

> CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'root.configuration' doesn't exist

Any Ideas?

**Comment by charlesportwoodii** [comment]
The box doesn't appear to be provisioned. Make sure the `vagrant up --provision` task actually provisions the box. After running `vagrant destroy` that the box is _fully_ destroyed in Virtualbox before bringing the box back up.

**Comment by charlesportwoodii** [comment]
@whsecurity,

Were you able to resolve your issue?
